#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Software License Agreement (BSD License)
#
# Copyright (c) 2008, Willow Garage, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of Willow Garage, Inc. nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#


## 重映射tf话题

from __future__ import print_function

import rospy
from tf.msg import tfMessage
from std_msgs.msg import Empty

# TfRemapper类用于重映射tf消息中的frame_id和child_frame_id。
class TfRemapper:
    """
    TfRemapper类用于重映射tf消息中的frame_id和child_frame_id。
    """
    def __init__(self):
        """
        __init__(self)
        @brief 构造函数，初始化TfRemapper。
        它会创建一个tf消息的发布者，并从ROS参数服务器获取映射规则。
        然后订阅旧的tf话题，以便进行重映射。
        """
        # 创建一个发布者，将重映射后的tf消息发布到/tf话题。
        self.pub = rospy.Publisher('/tf', tfMessage, queue_size=1)
        # 从ROS参数服务器获取名为'~mappings'的参数，如果不存在则默认为空列表。
        mappings = rospy.get_param('~mappings', [])
        self.mappings = {}

        # 遍历映射规则，将旧的frame_id映射到新的frame_id。
        for i in mappings:
            if "old" in i and "new" in i:
                self.mappings[i["old"]] = i["new"]

        print("Applying the following mappings to incoming tf frame ids", self.mappings)
        # 订阅旧的tf话题/tf_old，当接收到消息时调用callback方法进行处理。
        rospy.Subscriber("/tf_old", tfMessage, self.callback)

    def callback(self, tf_msg):
        """
        callback(self, tf_msg)
        @brief tf消息的回调函数，用于重映射frame_id和child_frame_id。
        @param tf_msg: 接收到的tfMessage消息。
        """
        # 遍历tf消息中的每一个TransformStamped，根据映射规则修改frame_id和child_frame_id。
        for transform in tf_msg.transforms:
            if transform.header.frame_id in self.mappings:
                transform.header.frame_id = self.mappings[transform.header.frame_id]
            if transform.child_frame_id  in self.mappings:
                transform.child_frame_id = self.mappings[transform.child_frame_id]

        # 发布重映射后的tf消息。
        self.pub.publish(tf_msg)

# remap_tf函数，用于发布一个空的Empty消息。
# 注意：此函数在当前脚本中未被直接调用，可能是一个占位符或用于其他目的。
def remap_tf():
    """
    remap_tf()
    @brief 发布一个空的Empty消息。
    此函数在当前脚本中未被直接调用，可能是一个占位符或用于其他目的。
    """
    pub.publish(Empty())

# 主函数入口
if __name__ == '__main__':
    # 初始化ROS节点，节点名为'tf_remap'。
    rospy.init_node('tf_remap')
    # 创建TfRemapper类的实例，开始进行tf消息的重映射。
    TfRemapper()
    # 进入ROS的事件循环，等待回调函数被调用。
    rospy.spin()
